changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Sections
      labels:
        - new-section
    - title: New Pages
      labels:
        - new-page
    - title: Updated Pages
      labels:
        - update-page
    - title: Infrastructure Changes
      labels:
        - update-infra
    - title: Other Changes
      labels:
        - "*"
