name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  # docs only: markdown linters run every Saturday at 11:00am UTC
  # to check for links that have died
  schedule:
    - cron: '0 11 * * 6'
  workflow_dispatch:

# Cancel in-progress runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # CI for all UBCSailbot repositories defined in one place
  # Runs another workflow: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  test-definitions:
    # sailbot_workspace: use locally-defined file
    # other repositories: set to UBCSailbot/sailbot_workspace/.github/workflows/test_definitions.yml@<release>
    uses: UBCSailbot/sailbot_workspace/.github/workflows/test_definitions.yml@main
    # see https://github.com/UBCSailbot/sailbot_workspace/blob/main/.github/workflows/test_definitions.yml
    # for documentation on the inputs and secrets below
    with:
      repository: ${{ github.event.repository.name }}
      ros-ci: false
      clang-tidy: false
      rebuild-docs: false
    # If rebuild-docs is true:
    # 1. Create the repository secret PAT_TOKEN (copy from Bitwarden)
    # 2. Uncomment the 2 lines below
    # secrets:
    #   gh-token: ${{ secrets.PAT_TOKEN }}

  markdown-link-redirection-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check links to external sites redirect to a new tab
        uses: ./.github/actions/lint/
        env:
          ROOT: './docs/'
